[package]
name = "leak"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "leak"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.16.2"
pyo3 = { version = "0.16.1", features = ["extension-module"] }